# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yewong.me
title: Security Software Desigin
email: wangye@udel.edu
author: Ye Wang
description:  # "Write an awesome description for your new site here. 
  'This is the showcase of CPEG674 'Security Software Desigin'
copyright: 'Copyright &copy; 2016 Ye Wang. All Rights Reserved.'
credits: 'This is the showcase of CPEG674 'Security Software Desigin'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/Ye__Wang
  - title: github
    url: https://github.com/YeWang0
  - title: linkedin
    url: https://www.linkedin.com/in/ye-wang
