

# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yewong.me
title: Security Software Desigin
email: wangye@udel.edu
author: Ye Wang
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016 Ye Wang.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/Ye__Wang
  - title: github
    url: https://github.com/YeWang0
  - title: linkedin
    url: https://www.linkedin.com/in/ye-wang
